LABEL \
  version="0.1" \
  maintainer="computeronix" \
  release-date="02-06-2021" \
  website="https://aka.wf/ai6"
  description="docker container with base image ubuntu containing chrony with default settings"

FROM ubuntu:latest AS chrony-ubuntu
ENV DIR="/tmp"
    
WORKDIR "${DIR}"

RUN "apt-get update && apt-get -y install chrony systemctl && rm -rf /var/lib/apt/lists/* && systemctl enable --now chrony"
