FROM alpine:3.18.3 AS chrony-alpine

LABEL \
  maintainer="computeronix" \
  website="https://aka.wf/ai6" \
  description="docker container with base image alpine and updates, with wget, python3, modified systemctl, and chrony. chrony has default settings and auto-starts."

ENV SYSTEMCTL="https://raw.githubusercontent.com/gdraheim/docker-systemctl-replacement/master/files/docker/systemctl3.py"

RUN apk update && apk add --no-cache python3 chrony && rm -rf /var/lib/apt/lists/*
RUN wget $SYSTEMCTL -O /usr/bin/systemctl && chmod +x /usr/bin/systemctl
#systemctl enable --now chrony
