FROM debian:12 AS chrony-debian

LABEL \
  maintainer="computeronix" \
  website="https://aka.wf/ai6" \
  description="docker container with base image centos and updates, with wget, python3, modified systemctl, and chrony. chrony has default settings and auto-starts."

ENV SYSTEMCTL="https://raw.githubusercontent.com/gdraheim/docker-systemctl-replacement/master/files/docker/systemctl3.py"

RUN apt-get update && apt-get -y install wget python3 chrony && rm -rf /var/lib/apt/lists/*
RUN wget $SYSTEMCTL -O /usr/bin/systemctl && chmod +x /usr/bin/systemctl && systemctl enable --now chronyd
